mysql:
  image:
    repository: mysql
    tag: 8.0
  replicas: "1"
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  env:
    database: wordpress
    user: wordpress
  service:
    ClusterIP: None
  pvc:
    accessModes: ReadWriteOnce
    storageSize: "20Gi"
  secret:
    password: c3VrYXJ5YXN1a2Fy


wordpress:
  image:
    repository: wordpress
    tag: 6.2.1-apache
  replicas: "1"
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: LoadBalancer
  pvc:
    accessModes: ReadWriteOnce
    storageSize: "20Gi"


serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
